//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceTarea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.TareasPorUsuario = new HashSet<TareasPorUsuario>();
            this.UsuarioAutenticacion = new HashSet<UsuarioAutenticacion>();
            this.UsuarioReclamo = new HashSet<UsuarioReclamo>();
            this.UsuarioRol = new HashSet<UsuarioRol>();
        }
    
        public string IdUsuario { get; set; }
        public string Correo { get; set; }
        public bool EmailConfirmacion { get; set; }
        public string Contrasena { get; set; }
        public string Seguridad { get; set; }
        public string Telefono { get; set; }
        public bool TelefonoConfirmacion { get; set; }
        public bool FactoresActivacion { get; set; }
        public Nullable<System.DateTime> FechaBloqueo { get; set; }
        public bool Bloqueo { get; set; }
        public int IngresosFallidos { get; set; }
        public string EmailUsuario { get; set; }
        public string Discriminator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TareasPorUsuario> TareasPorUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioAutenticacion> UsuarioAutenticacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioReclamo> UsuarioReclamo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioRol> UsuarioRol { get; set; }
    }
}
